application: si-age-league
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
  
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /api/players/.*
  script: api.players.app

- url: /api/users/.*
  script: api.users.app

- url: /api/games/.*
  script: api.games.app
  
- url: /api/civs/.*
  script: api.civs.app

- url: /api/gamesettings/.*
  script: api.gamesettings.app

- url: /api/globalstats/.*
  script: api.globalstats.app

- url: /api/rules/.*
  script: api.rules.app

- url: /api/actions/admin/.*
  script: api.actions_admin.app

- url: /api/actions/.*
  script: api.actions.app

- url: /.*
  script: main.app

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

builtins:
- deferred: on

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest