application: si-age-league
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
  
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /api/players/.*
  script: api.players.app

- url: /api/games/.*
  script: api.games.app
  
- url: /api/civs/.*
  script: api.civs.app

- url: /api/gamesettings/.*
  script: api.gamesettings.app
  
- url: /api/.*
  script: api.general.app
  
- url: /admin/.*
  script: admin.app
  login: admin

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest